### PR TITLE
Do not require compilers as run-time dependency and build fixes

### LINKED ISSUE #6: sdsl-lite version 2.1.1=hc9558a2_1001 installs an old compiler
I am trying to install the CXX compiler and the latest version of sdsl-lite (`2.1.1=hc9558a2_1001`) in an environment. However, it only allows to install version gxx version 7.5, which is quite old.
I suspect that this line
https://github.com/conda-forge/sdsl-lite-feedstock/blob/48787208c706f269dfea27a741c8f2a3a0d15e99/recipe/meta.yaml#L25
can be safely removed and that the removal could solve my issue.

### PR DESCRIPTION
**Pull request by yp**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [X] Bumped the build number (if the version is unchanged)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Fix: #6 

The PR move the CXX compiler from run requirements to test requirements so that the compiler is not listed as run-time dependency.
As an additional build-time test, the build process now also compiles a test case that includes all the files of the library.

The process also removes the files of the Google Test library in order to avoid possible clashes.

I also included some fixes that are committed in sdsl-lite repository but not officially released (the latest release is more than 5 years old) as patches.

### CODE REVIEW

**Comment by johnlees** [comment]
@yp would you be happy to be added as a recipe maintainer?

**Comment by yp** [comment]
@johnlees Yes, I am always happy when I can contribute.

I hope the recipe is in good shape now.

**Comment by johnlees** [comment]
Excellent, thank you for the update!

And thanks also for volunteering to help maintain. If you add your username to the maintainer list as part of this PR I'll merge when the tests pass.

**Comment by johnlees** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
